// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180813222909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Boss", b =>
                {
                    b.Property<int>("BossId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("BossId");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("Data.Models.DiscordUser", b =>
                {
                    b.Property<string>("DiscordUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("DiscordUserId");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BossId");

                    b.Property<string>("Name");

                    b.Property<string>("PlayerDiscordUserId");

                    b.HasKey("RoleId");

                    b.HasIndex("BossId");

                    b.HasIndex("PlayerDiscordUserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Data.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BossId");

                    b.Property<string>("HostDiscordUserId");

                    b.Property<int>("Limit");

                    b.Property<DateTime>("Time");

                    b.HasKey("SessionId");

                    b.HasIndex("BossId");

                    b.HasIndex("HostDiscordUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Data.Models.Role", b =>
                {
                    b.HasOne("Data.Models.Boss")
                        .WithMany("Roles")
                        .HasForeignKey("BossId");

                    b.HasOne("Data.Models.DiscordUser", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerDiscordUserId");
                });

            modelBuilder.Entity("Data.Models.Session", b =>
                {
                    b.HasOne("Data.Models.Boss", "Boss")
                        .WithMany()
                        .HasForeignKey("BossId");

                    b.HasOne("Data.Models.DiscordUser", "Host")
                        .WithMany()
                        .HasForeignKey("HostDiscordUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
